title:            Yalov
description:      'Personal page'

repository: yalov/yalov.github.io

imgfolder: /images/

author:
  name:           'Yalov Alexander'
  email:            mailto://alexander.yalov@gmail.com

permalink: :year/:title
url:              https://yalov.github.io
baseurl:          ""
highlighter:      rouge

paginate:         5
paginate_path: "/page/:num/"

excerpt_separator: <!--more-->

disqus_name: yalov-github

markdown:         kramdown
kramdown:
smart_quotes: ["apos", "apos", "quot", "quot"]

  # smart_quotes:
  #
  #   first parameter : how an opening apostrophe is transformed
  #                     or apostrophe like in "I'm"
  #           default : ' -> ‘ (lsquo)
  #              apos : ' -> '
  #
  #   second parameter : how a closing apostrophe is transformed
  #           default : ' -> ’ (rsquo)
  #              apos : ' -> '
  #
  #   third parameter : how an opening double quote is transformed
  #           default : " -> “ (ldquo)
  #              quot : " -> "
  #
  #   fourth parameter : how a closing double quote is transformed
  #           default : " -> ” (rdquo)
  #              quot : " -> "
  #
  #   Default kramdown config
  #     smart_quotes: ["rdquo", "rsquo", "ldquo", "rdquo"]
  #
  #   Programmer's world compliant config :
  #    smart_quotes: ["apos", "apos", "quot", "quot"]





gems:
  - jekyll-paginate
#  - jekyll-seo-tag
  - jekyll-hist
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-redirect-from
