title:            Yalov
description:      'Personal page'

# This is for {{site.github.repository_url}} and others working at localhost
repository: yalov/yalov.github.io

imgfolder: /images/

author:
  name:           'Yalov Alexander'
  email:           alexander.yalov@gmail.com
  fb:              a.yalov
  patreon:         https://www.patreon.com/yalov

fb_app_id:           000000000000000
yandex-verification: 442075101e0961a9

permalink: /:categories/:title
url:              https://yalov.github.io   # no ending /
baseurl:          ""                        # no ending /

highlighter:      rouge

paginate:         20
paginate_path: "/page/:num/"

excerpt_separator: <!--more-->

disqus_name: yalov-github
comments: false

markdown:         kramdown
kramdown:
smart_quotes: ["apos", "apos", "quot", "quot"]

# Read Time is a calculator to provide post Estimated Reading Time (ERT) based on word count. Usage is recommended.
readtime:		true
words_per_minute:			180

collections:
  collection:
    output: true
    permalink: /:categories/:title

# fixing warning on 'bundle exec jekyll serve'  
# the warning: 'GitHub Metadata: No GitHub API authentication could be found. 
# Some fields may be missing or have incorrect data.'
# but {{site.github.versions}} and other doesn't work
# github: [metadata]

plugins:
  - jekyll-paginate
#  - jekyll-seo-tag
  - jekyll-hist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
