title:            Yalov
description:      'Personal page'

repository: yalov/yalov.github.io

author:
  name:           'Yalov Alexander'
  email:            mailto://alexander.yalov@gmail.com

permalink: :year/:title
url:              https://yalov.github.io
baseurl:          ""
markdown:         kramdown
highlighter:      rouge

paginate:         3
paginate_path: "/page/:num/"

excerpt_separator: <!--more-->

disqus_name: yalov-github








gems:
  - jekyll-paginate
#  - jekyll-seo-tag
  - jekyll-hist
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-redirect-from
