title:            Yalov
description:      'Personal page'

# This is for {{site.github.repository_url}} and others working at localhost
repository: yalov/yalov.github.io

imgfolder: /images/

author:
  name:           'Yalov Alexander'
  email:           alexander.yalov@gmail.com
  fb:              a.yalov

fb_app_id:           407579492909554
yandex-verification: 442075101e0961a9

permalink: /:categories/:title
url:              https://yalov.github.io
baseurl:          ""
highlighter:      rouge

paginate:         20
paginate_path: "/page/:num/"

excerpt_separator: <!--more-->

disqus_name: yalov-github

markdown:         kramdown
kramdown:
smart_quotes: ["apos", "apos", "quot", "quot"]


collections:
  collection:
    output: true
    permalink: /:categories/:title

  # smart_quotes:
  #
  #   first parameter : how an opening apostrophe is transformed
  #                     or apostrophe like in "I'm"
  #           default : ' -> ‘ (lsquo)
  #              apos : ' -> '
  #
  #   second parameter : how a closing apostrophe is transformed
  #           default : ' -> ’ (rsquo)
  #              apos : ' -> '
  #
  #   third parameter : how an opening double quote is transformed
  #           default : " -> “ (ldquo)
  #              quot : " -> "
  #
  #   fourth parameter : how a closing double quote is transformed
  #           default : " -> ” (rdquo)
  #              quot : " -> "
  #
  #   Default kramdown config
  #     smart_quotes: ["rdquo", "rsquo", "ldquo", "rdquo"]
  #
  #   Programmer's world compliant config :
  #    smart_quotes: ["apos", "apos", "quot", "quot"]





gems:
  - jekyll-paginate
#  - jekyll-seo-tag
  - jekyll-hist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
