title:            Yalov
description:      'Personal page'

# This is for {{site.github.repository_url}} and others working at localhost
repository: yalov/yalov.github.io

imgfolder: /images/

author:
  name:           'Yalov Alexander'
  email:           alexander.yalov@gmail.com
  fb:              a.yalov

fb_app_id:           000000000000000
yandex-verification: 442075101e0961a9

permalink: /:categories/:title
url:              https://yalov.github.io   # no ending /
baseurl:          ""                        # no ending /

highlighter:      rouge

paginate:         20
paginate_path: "/page/:num/"

excerpt_separator: <!--more-->

disqus_name: yalov-github

markdown:         kramdown
kramdown:
smart_quotes: ["apos", "apos", "quot", "quot"]


collections:
  collection:
    output: true
    permalink: /:categories/:title






gems:
  - jekyll-paginate
#  - jekyll-seo-tag
  - jekyll-hist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
